language: java

cache:
    directories:
        - $HOME/.m2

jobs:
    include:
        - stage: test
          addons:
            sonarcloud:
                organization: "kiliandeca"
                token:
                    secure: "$SONAR_TOKEN"
          script:
            - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Kiliandeca_sample-application-students

        - stage: build
          services:
            - docker
          script:
            # Build Java
            - mvn package -DskipTests

            #Build Docker
            - docker build -t kiliandeca/sample-cpe:api sample-application-http-api-server
            - docker build -t kiliandeca/sample-cpe:db sample-application-db-changelog-job

            # Publish
            - docker login -u kiliandeca -p $DOCKER_HUB_SECRET
            - docker push kiliandeca/sample-cpe:api
            - docker push kiliandeca/sample-cpe:db