language: java
services:
    - docker
script:
    - mvn dependency:go-offline
    - mvn clean verify
    - docker login -u kiliandeca -p $DOCKER_HUB_SECRET
    - docker build -t kiliandeca/sample-cpe .
    - docker push kiliandeca/sample-cpe
cache:
    directories:
        - $HOME/.m2